name: Primer workflow

on: 
  push:
    branches:
      - main  
jobs:
  hola_mundo:
    runs-on: ubuntu-latest

    steps:
      - name: Bajar codigo
        uses: actions/checkout@v4
      - name: Instalar pytest
        run: pip install pytest
      - name: Probar codigo
        run: pytest test.py
